Backend: Vitis
ClockPeriod: 10
HLSConfig:
  LayerName:
    dec_act1:
      ReuseFactor: 1
      Strategy: Resource
    dec_act2:
      ReuseFactor: 1
      Strategy: Resource
    dec_conv1:
      ReuseFactor: 1
      Strategy: Resource
    dec_conv1_linear:
      Precision:
        result: fixed<8,1>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    dec_conv2:
      ReuseFactor: 1
      Strategy: Resource
    dec_conv2_linear:
      Precision:
        result: fixed<8,1>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    dec_dense:
      ReuseFactor: 1
      Strategy: Resource
    dec_dense_act:
      ReuseFactor: 1
      Strategy: Resource
    dec_dense_linear:
      Precision:
        result: fixed<8,1>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    dec_out_act:
      ReuseFactor: 1
      Strategy: Resource
    dec_out_conv:
      ReuseFactor: 1
      Strategy: Resource
    dec_out_conv_linear:
      Precision:
        result: fixed<8,1>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    dec_reshape:
      ReuseFactor: 1
      Strategy: Resource
    dec_up1:
      ReuseFactor: 1
      Strategy: Resource
    dec_up2:
      ReuseFactor: 1
      Strategy: Resource
    enc_act1:
      ReuseFactor: 1
      Strategy: Resource
    enc_act2:
      ReuseFactor: 1
      Strategy: Resource
    enc_conv1:
      ReuseFactor: 1
      Strategy: Resource
    enc_conv1_linear:
      Precision:
        result: fixed<8,1>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    enc_conv2:
      ReuseFactor: 1
      Strategy: Resource
    enc_conv2_linear:
      Precision:
        result: fixed<8,1>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    enc_pool1:
      ReuseFactor: 1
      Strategy: Resource
    enc_pool2:
      ReuseFactor: 1
      Strategy: Resource
    flatten:
      ReuseFactor: 1
      Strategy: Resource
    input_1:
      ReuseFactor: 1
      Strategy: Resource
    latent_act:
      ReuseFactor: 1
      Strategy: Resource
    latent_space:
      ReuseFactor: 1
      Strategy: Resource
    latent_space_linear:
      Precision:
        result: fixed<8,1>
        table: fixed<18,8>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: fixed<8,1>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_stream
InputData: null
KerasModel: !keras_model '../hls_output/keras_model.h5'
OutputDir: ../hls_output
OutputPredictions: null
Part: xc7a35tcsg324-1
ProjectName: myproject
Stamp: 378d3ba2
